
image: docker:19.03.12  

stages:
    - deploy

step-deploy-production:
    stage: deploy
    before_script:
        - export DYNAMIC_ENV_VAR=PRODUCTION
    only:
        - production
    tags:
        - production
    script:
        - echo setting up env $DYNAMIC_ENV_VAR
        - apt-get install -y python-pip
        - pip install docker-compose
        - docker image prune -f
        - docker-compose -f docker-compose.yml build --no-cache
        - docker-compose -f docker-compose.yml up -d