version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_SERVER=http://api.mexle.org/
      - REACT_APP_PUBLIC_URL=http://mexlefrontend.ddns.net/
    volumes:
      - '.:/app'
      - '/app/node_modules'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sample.rule=Host(`mexlefrontend.ddns.net`)"
      - "traefik.http.routers.sample.entrypoints=web"
    networks: 
      - default

networks:
  default:
    external:
      name: gateway