version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    labels:
       - "traefik.http.routers.sample.rule=Host(`mexlefrontend.ddns.net`)"
    environment:
      - CHOKIDAR_USEPOLLING=true