version: '3'

services:
  mexlefrontend:
    image: "mexlefrontend:B${BUILD_NUMBER}"
    build:
      context: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`mexlefrontend.ddns.net`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.docker.network=web"    
  integration:
    depends_on:
      - mexlefrontend
    image: "mexlefrontend:test-B${BUILD_NUMBER}"
    build:
      context: .
      dockerfile: Dockerfile.Integration
    environment:
      - TEAMCITY_PROJECT_NAME