version: '3'

services:
  mexlefrontend:
    image: "mexlefrontend:B${BUILD_NUMBER}"
    build:
      context: .
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.reactboilerplate.frontend.rule=Host:mexlefrontend.ddns.net"
      - "traefik.reactboilerplate.frontend.port=3000"
      - "traefik.reactboilerplate.frontend.protocol=web"
    
  integration:
    depends_on:
      - mexlefrontend
    image: "mexlefrontend:test-B${BUILD_NUMBER}"
    build:
      context: .
      dockerfile: Dockerfile.Integration
    environment:
      - TEAMCITY_PROJECT_NAME