version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`mexle.org`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    networks: 
      - default

networks:
  default:
    external:
      name: gateway