version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sample.rule=Host(`mexlefrontend.ddns.net`)"
      - "traefik.http.routers.sample.entrypoints=web"
    environment:
      - CHOKIDAR_USEPOLLING=true