version: '3'

services:
  mexlefrontend:
    image: "node:12.20.1-buster"
    container_name: mexlefrontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`mexlefrontend.ddns.net`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.docker.network=web"